global_frame: map
robot_base_frame: base_footprint
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.26, 0.27],[0.26,0.27],[0.26,-0.27],[-0.26,-0.27]]
# robot_radius: ir_of_robot
inflation_radius: 0.45

observation_sources: laser_scan_front laser_scan_rear 

laser_scan_front: {sensor_frame: base_laser_link_0, data_type: LaserScan, topic: /base_scan_0, expected_update_rate: 1.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}

laser_scan_rear: {sensor_frame: base_laser_link_1, data_type: LaserScan, topic: /base_scan_1, expected_update_rate: 1.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
