local_costmap:
  global_frame: /map                    # default : /map
  inflation_radius: 0.6                 # default : 0.46
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  plugins: 
  - name: static_map
    type: "costmap_2d::StaticLayer"
  - name: obstacles
    type: "costmap_2d::VoxelLayer"
  - name: inflation
    type: "costmap_2d::InflationLayer"
